# Generated by Django 4.2.6 on 2023-10-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_desc_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='ctg',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='desc',
        ),
    ]
