# Generated by Django 4.2.6 on 2023-11-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ctg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='../static/images/default.png', upload_to=''),
        ),
    ]
