# Generated by Django 4.2.6 on 2023-11-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_ctg_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='../static/images/default.png', upload_to=''),
        ),
    ]
