# Generated by Django 4.2.6 on 2023-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_userid_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orederdetails',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
